# APP NAME
spring.application.name=measurement-service

# PORT (RAILWAY)
server.port=${PORT:8080}

# CONTEXT PATH
server.servlet.context-path=/measurement

# =========================
# EUREKA (CRITICAL)
# =========================
eureka.client.service-url.defaultZone=https://quantitymeasurementappdeploy-production.up.railway.app/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# =========================
# INSTANCE CONFIG (FIXED)
# =========================
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=quantitymeasurementappdeploy.onrender.com
eureka.instance.instance-id=${spring.application.name}:${random.value}
