# APP NAME
spring.application.name=measurement-service

# PORT (RAILWAY)
server.port=${PORT:8080}

# CONTEXT PATH (KEEP THIS — GOOD)
server.servlet.context-path=/measurement

# =========================
# EUREKA (CRITICAL)
# =========================
eureka.client.service-url.defaultZone=https://quantitymeasurementappdeploy-production.up.railway.app/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# OPTIONAL (GOOD PRACTICE)
eureka.instance.prefer-ip-address=true
